### PR TITLE
Replace tail recursion with while loop

### LINKED ISSUE #1087: AsyncEnumerable.ToObservable() uses tail recursion and overflows the stack
`AsyncEnumerable.Range(0, 10000).ToObservable()`

Replacing tail recursion with while loop fixes the issue.

### PR DESCRIPTION
**Pull request by bartholinie**
Fixes #1087

### CODE REVIEW

**Comment by quinmars** [comment]
Note, that #915 also removes the tail recursion.

**Comment by akarnokd** [comment]
I prefer #915 too. @quinmars Could you add the test from this PR to yours?

**Comment by quinmars** [comment]
I will do that this evening (CET). I hopefully can preserve the authorship with cherry picking.

**Comment by danielcweber** [comment]
Fixed by #915. Unit test from this PR made it there. Thank you for the effort.

**Pull request closed without merging**
