### PR TITLE
nuget badges link to package website

### PR DESCRIPTION
**Pull request by cloudRoutine**

### CODE REVIEW

**Comment by onovotny** [comment]
Hi @cloudRoutine, thanks for the PR! To round this out, would you mind adding links to the MyGet and AppVeyor build definitions as well?

**Comment by cloudRoutine** [comment]
There aren't as clear cut destinations to link to for those, that's why I didn't do it in the first place

**Comment by onovotny** [comment]
Lets go with the Rx Gallery for MyGet: https://dotnet.myget.org/gallery/rx, and Ix's CI feed is https://ci.appveyor.com/project/dotnetfoundation/rx-net-g0jsj and Rx's CI feed is https://ci.appveyor.com/project/dotnetfoundation/rx-net-la3iv. The badges may need to be updated for CI as well as we did create separate CI builds for Rx/Ix and did not yet updated the badges.

**Comment by akarnokd** [comment]
I think this can be closed.

**Pull request closed without merging**
