### PR TITLE
Add Github welcome issue/PR templates

### LINKED ISSUE #187: add issue & pull request templates to repo
Opening this up to source suggestions for what we should capture to ensure:
- issues are detailed and reproducible by others
- pull requests are easy to understand when opened (or maybe this doesn't matter right now)

### PR DESCRIPTION
**Pull request by akarnokd**
This PR adds GitHub templates so new Issues or PRs are welcomed with questions and instructions. 

I've tried to incorporate as much OSS support experience (with *RxJava* and with *dotnet/reactive*) as I could as politely as seemed reasonable.

Resolves #187

### CODE REVIEW

**Comment by akarnokd** [comment]
> have different templates for

Good idea, not sure how to do it though.

**Comment by onovotny** [comment]
Take a look at the templates in dotnet-foundation/projects

**Comment by akarnokd** [comment]
Done. I didn't split further along bug/enhancement/feature/question because it often requires evaluation (i.e., asked like a question but it is actually a bug).

**Comment by akarnokd** [comment]
The issue template choser works, but the pull request template doesn't. I get a blank PR. Looks like template choser for PRs is not supported.

**Pull request merged**
