### PR TITLE
Update config

### PR DESCRIPTION
**Pull request by onovotny**
This .editorconfig is mostly the same as the existing one but rearranged.

PR also contains code fixes using VS 2017 15.8 p3's format document that applies the styles.

### CODE REVIEW

**Comment by akarnokd** [comment]
I won't be able to check this until next morning.

**Comment by onovotny** [comment]
That's fine, I'm still fixing styles

**Comment by akarnokd** [comment]
It would be great if this got merged as it prevents further developments due to likely conflicts.

**Pull request merged**
