### PR TITLE
AsyncRx: Avoid closure allocations in Linq-operators when only the source-observable is captured.

### PR DESCRIPTION
**Pull request by danielcweber**
This avoids quite a few allocations of closures for Linq-operator-creation when the only object that would have been captured is the source-observable. More closure-allocation improvements may follow.

### CODE REVIEW

**Comment by bartdesmet** [comment]
LGTM. We can also mark lambdas without a closure as static from now on.

**Comment by danielcweber** [comment]
I'll update this PR tomorrow to enable C# 9

**Comment by danielcweber** [comment]
>I'll update this PR tomorrow to enable C# 9

Did it in a separate PR in #1365 because it'll need separate review w.r.t. all the CI properties. @clairernovotny Would you please have a look?

**Comment by danielcweber** [comment]
Lambdas have been marked static.

**Review by cabauman — APPROVED** [review]

**Pull request merged**
