### PR TITLE
Add non-recursive extensions for IScheduler allowing to return an IDisposable

### PR DESCRIPTION
**Pull request by danielcweber**
This will enable more usages of non-recursive scheduling. Before C# 7.3, the compiler will complain about some ambiguities, so we increase the language version.

### CODE REVIEW

**Comment by akarnokd** [comment]
"System.Security.VerificationException : Operation could destabilize the runtime."?

**Comment by danielcweber** [comment]
Maybe https://github.com/dotnet/roslyn/issues/27382. Investigating.

**Comment by danielcweber** [comment]
Removing `[assembly: AllowPartiallyTrustedCallers]` makes it disappear. I have to investigate which direction to go here, the language version has to be able to progress.

**Comment by danielcweber** [comment]
More reference: https://twitter.com/jonskeet/status/1002876525119754240

**Comment by danielcweber** [comment]
Removing `readonly` from [this](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Linq/Observable/GroupBy.cs#L16) also does the trick.

**Comment by onovotny** [comment]
Thread says to remove APTCA:
https://twitter.com/onovotny/status/1012392223755980800

**Comment by onovotny** [comment]
And the docs are changing to say this directly too: https://github.com/dotnet/docs/pull/6199

**Pull request merged**
