### PR TITLE
Documentation for Ix.NET

### PR DESCRIPTION
**Pull request by waf**
The Ix.NET project is well-documented in the source code, but there's no web-browsable documentation.

This PR is against the `gh-pages` branch of this repo, and adds documentation generated from the source, using [SandCastle](https://github.com/EWSoftware/SHFB/wiki).

You can see the documentation available at my gh-pages fork, available here: http://fuqua.io/Rx.NET/ (scroll down to the Ix.NET section). Here's a [direct link to the generated documentation](http://fuqua.io/Rx.NET/ix-docs/).

Inside the `ix-docs` directory, there is a README and SandCastle project for regenerating the documentation.

---

This change is [Reviewable](https://reviewable.io/reviews/reactive-extensions/rx.net/160)

### CODE REVIEW

**Comment by aalmada** [comment]
What about using DocFX instead of Sandcastle? 
http://dotnet.github.io/docfx/
https://channel9.msdn.com/Blogs/Seth-Juarez/An-Introduction-to-DocFX

**Comment by shiftkey** [comment]
@onovotny can you give a quick TL;DR here for what you had in mind about documentation?

**Comment by martinwoodward** [comment]
Hi @waf - while the team are looking into this one, would you mind signing the [.NET Foundation Contribution License agreement](http://cla2.dotnetfoundation.org)? Shouldn't take long and is hopefully pretty painless. Many thanks!

**Comment by waf** [comment]
@martinwoodward thanks, signed. I'm happy to look at integrating docfx instead, if that's the route the team wants to go.

**Comment by waf** [comment]
I see the `cla-signed` label was just removed. Should I re-sign the CLA?

BTW, is there any feedback from the team I can work on, or can we merge this? My demo website is unfortunately [becoming highly ranked on google](https://www.google.com/search?q=Ix.NET+QueryableEx), which was not the intention.

I've used DocFx on some other projects now, and in my opinion SandCastle provides more user-friendly documentation as well as being more configurable. However, I'm happy to set up docfx if that's desired.

**Comment by onovotny** [comment]
Closing due to age. Will revisit as C# 8 gets closer.

**Pull request closed without merging**
