### PR TITLE
4.x: Refactor Linq operator unit tests into separate files/classes

### PR DESCRIPTION
**Pull request by akarnokd**
This PR refactors the various operator unit tests into their separate files and allows:

- locating tests of an operator by name instead of a category,
- running tests of one operator instead of a group of operators.

### CODE REVIEW

**Comment by akarnokd** [comment]
Now the fun part. Finding out which is that 1 test that didn't run twice:

image

image

**Comment by onovotny** [comment]
@akarnokd that could be due to the removal of some of the TFM's. We removed netcoreapp1.1, so that could account for one test depending on what the base version is.

**Comment by akarnokd** [comment]
I was verifying periodically if the test runner still has the original 3534 test listed and it still shows me that:

image

>that could be due to the removal of some of the TFM's. 

This shows 7010 as well:

image

**Comment by danielcweber** [comment]
Can you build it locally through the script, it should open a coverage report at the end, if it didn't decrease, it'll be good to merge.

**Comment by akarnokd** [comment]
Looks like there were changes on the master earlier and [I compared against another PR](https://github.com/dotnet/reactive/pull/527#issuecomment-391870107) probably pointing further back in time.

**Pull request merged**
