### PR TITLE
4.x: LongCount() don't init to default zero

### PR DESCRIPTION
**Pull request by akarnokd**
There is no reason to initialize the `_count` to its default zero value.

### CODE REVIEW

**Comment by danielcweber** [comment]
Will merge as soon as this WIP-bot becomes alive again....

**Comment by danielcweber** [comment]
According to [this](https://stats.uptimerobot.com/Dq46zf6PY) it's not down...

**Comment by danielcweber** [comment]
Updating the branch didn't help either.

**Comment by akarnokd** [comment]
I've renamed the PR to `[WIP]`, then renamed it back and now the WIP service seems to be working again.

**Pull request merged**
