### PR TITLE
The approved API of Qbservable.RetryWhen() has the wrong return type.

### PR DESCRIPTION
**Pull request by quinmars**
It should return an `IQbservable` instead of an `IObservable`.

### CODE REVIEW

**Comment by ryanwersal** [comment]
Is the issue that `PublicApiGenerator` is producing an incorrect interpretation of the public API surface? If so, I'll have to dig into that library and find out why...

**Comment by quinmars** [comment]
@ryanwersal, no worries, the generator works correct. It's the source that is wrong. To fix that I already have a pending PR. ;)

**Comment by ryanwersal** [comment]
@quinmars Ah, good. I unfortunately don't know the API much so I couldn't tell myself - thanks for the confirmation! I should have a PR submitted tonight that will fix the NRE when the tests fail and output some sort of reasonable diff in the build logs.

**Comment by quinmars** [comment]
@ryanwersal very nice! I really appreciate the API approval tests.

**Comment by danielcweber** [comment]
>To fix that I already have a pending PR. ;)

@quinmars That's #537? Is it still a work in progress? To make this build you would have to manually fix the code in Qbservable.Generated as well, otherwise the build will remain broken.

**Comment by quinmars** [comment]
No, it will build. I just fixed a wrong test. Of course the test will fail, but that's fine, that's the job of unit tests. But I can integrate it in #537 if you prefer.

**Comment by danielcweber** [comment]
Sorry, didn't mean to close this PR...

**Comment by quinmars** [comment]
Nevermind, I already integrated into PR #537 and wil push it in some minutes.

**Comment by danielcweber** [comment]
>No, it will build. I just fixed a wrong test. Of course the test will fail, but that's fine, that's the job of unit tests. 

Right, what I mean, the CI will fail, so it won't allow me to merge your PR...

**Pull request closed without merging**
