### PR TITLE
Enhance AsyncLock to support passing state.

### PR DESCRIPTION
**Pull request by danielcweber**

### CODE REVIEW

**Comment by danielcweber** [comment]
Up to discussion: Should the public API be enhanced and the new internal method be made public?

**Comment by akarnokd** [comment]
I'm not convinced this is much of a win. the `object` state requires `struct`s to be boxed which is equivalent with having a capture of a struct inside a freshly allocated delegate.

**Comment by danielcweber** [comment]
Right, structs would need to be boxed, but I found most of the time, if something would need to be passed to AsyncLock, it's a class. Besides, even if boxing would need to occur, it's still one allocation less than closure+delegate.

**Comment by danielcweber** [comment]
So what's your proposal for a trampoline with state? Duplicate AsyncLock with a generic type parameter?

**Comment by akarnokd** [comment]
Yes, don't penalize the stateless user places.

**Comment by danielcweber** [comment]
That would work if all places in a class would only ever pass the same type of state. This might be the case in Rx but it would severely limit the usefulness of AsyncLock. Hence the object parameter.

**Comment by akarnokd** [comment]
Why would it be public? Support Rx primarily, also T can be object.

**Comment by danielcweber** [comment]
Will revisit after #558 is merged.

**Pull request merged**
