### PR TITLE
Added debugger display information to TestScheduler and HistoricalScheduler

### PR DESCRIPTION
**Pull request by paulomorgado**
This is very helpful when debugging tests.

### CODE REVIEW

**Comment by danielcweber** [comment]
@paulomorgado Nice idea. I wonder whether we want to have this for even more classes, e.g. all the observable implementations. I'm thinking outputting a readable representation of an operator chain. Then again, it might slow the debugger down big time...what do you think?

**Comment by paulomorgado** [comment]
It might, but only when evaluated.

But, for that use case, a debug visualizer might be a better match.

What do you think, @raffaeler?

**Comment by apobekiaris** [comment]
> @paulomorgado Nice idea. I wonder whether we want to have this for even more classes, e.g. all the observable implementations. I'm thinking outputting a readable representation of an operator chain. Then again, it might slow down the debugger big time...what do you think?

It may be great for some cases however at least in my projects I my experience is a really bad Vs behaviour when property evaluation is on. Consider making a switch off for this as well.

**Comment by paulomorgado** [comment]
How would I do this, @apobekiaris?

**Comment by apobekiaris** [comment]
> How would I do this, @apobekiaris?

Sorry no clue it just looked something that may affect me.

**Comment by paulomorgado** [comment]
ETW-like tracing would be nice, but that's another thing.

If I recall it correctly, debug visualizations are part of the type/object and debug vizualizers can be an add-on used only by the IDE and that it's not deployed with the library (like analyzers).

**Comment by paulomorgado** [comment]
Nevertheless, if anyone has suggestions for other types that would be nice to add debug vizualizers, I can add them.

**Comment by danielcweber** [comment]
@paulomorgado There's actually great potential in this approach I think. As you might know, we would like to optimize some code away but can't because [RxSpy](https://github.com/niik/RxSpy), an inspection tool for Rx, depends on certain internals. RxSpy is not in active development and it's unclear to me how widespread the use of RxSpy. A great deal of its functionality could maybe be replaced by visualizers...maybe....I'm just being visonary here.

**Comment by raffaeler** [comment]
@paulomorgado I did not mean to replace ETW tracing.
You are right about debugger visualizers. They are just a way for the debugger to "view" in an user-friendly way the state of an object.

**Comment by paulomorgado** [comment]
@raffaeler, I said ETW-like because .NET Core on non-Windows system doesn't exactly use ETW. Does it?

**Comment by raffaeler** [comment]
@paulomorgado The abstraction provided in aspnet core is the same for Windows and Linux. On Windows ETW is used. On Linux the abstraction uses LTTNG which is the 'official' way to trace.
The biggest difference is that ETW provides real-time tracing, while on Linux a file is created that you can analyze later either on Linux or on Windows.

**Comment by danielcweber** [comment]
@paulomorgado We have failing approval tests due to the added attributes on some types. Could you please fix them? I'll merge this PR then, more work on a smoother debugging experience is greatly appreciated!

**Comment by paulomorgado** [comment]
Done!

**Pull request merged**
