### PR TITLE
Added reactive libraries for Redux.NET

### PR DESCRIPTION
**Pull request by sujenk**
Hello and thank you for contributing to dotnet/reactive. Before you proceed by creating a pull request (PR):

What is the nature of your contribution?

#### Enhancement

I created this package: https://github.com/sujenk/Hyperyx.Core.Store
It provides libraries for redux in .NET Core. The reactive library seems to focus only on RxJs.
I think it's a good place for Redux as well. This is my first PR so forgive me if something isn't right.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1462) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1462) before we can accept your contribution.<br/><br/>:x: sujenk [sign now](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1462)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/reactive?pullRequest=1462) it.</sub>

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1462) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1462) before we can accept your contribution.<br/><br/>:x: sujenk [sign now](https://cla.dotnetfoundation.org/dotnet/reactive?pullRequest=1462)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/reactive?pullRequest=1462) it.</sub>

**Comment by akarnokd** [comment]
Hi. I don't see how your project is related to dotnet/reactive. There are no indications of cross-operations, or any form of dependencies on dotnet/reactive. 

Looking at the [source](https://github.com/sujenk/Hyperyx.Core.Store) and the [inspiring plugin](https://ngrx.io/), it is not clear why to include such kind of framework into dotnet/reactive specifically?

In addition, generally, extensions to dotnet/reactive require unit tests to show/verify the behavior and some documentation showing how to use said extensions.

**Comment by clairernovotny** [comment]
I'm closing this as out of scope for Rx.NET. It's certainly good to have more .NET libraries, but each should be in its own repo/project as appropriate.

**Pull request closed without merging**
